# =========================================================
# 0.1WILCOXON.py — Paired Wilcoxon Test from Checkpoint CSV
# =========================================================
import os
import sys
import pandas as pd
from scipy import stats

# Link root directory to import paths_config
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from paths_config import CHECKPOINT_FILE, LATEX_DIR

WILCOXON_LATEX_FILE = os.path.join(LATEX_DIR, "wilcoxon_variables.tex")

def main():
    print("=" * 70)
    print("0.1WILCOXON.py — Reading nested_cv_checkpoint.csv directly")
    print("=" * 70)

    if not os.path.exists(CHECKPOINT_FILE):
        print(f"[ERROR] {CHECKPOINT_FILE} not found. Run 0STACK.py first.")
        return

    df = pd.read_csv(CHECKPOINT_FILE)

    # Filter and sort by fold to guarantee exact pairing
    morgan = df[df['Mode'] == 'morgan'].sort_values('Fold')
    d3d = df[df['Mode'] == 'rdkit2d3d_fp'].sort_values('Fold')

    if len(morgan) == 0 or len(d3d) == 0:
        print("[ERROR] Could not find both 'morgan' and 'rdkit2d3d_fp' in checkpoint.")
        return

    mae_morgan = morgan['MAE_outer'].values
    mae_d3d = d3d['MAE_outer'].values

    print(f"Loaded {len(mae_morgan)} folds for 'morgan' and {len(mae_d3d)} folds for 'rdkit2d3d_fp'.")
    print(f"Mean MAE Morgan   : {mae_morgan.mean():.4f} +/- {mae_morgan.std():.4f}")
    print(f"Mean MAE 2D/3D/FP : {mae_d3d.mean():.4f} +/- {mae_d3d.std():.4f}")

    # Paired Wilcoxon Signed-Rank Test across the outer folds
    w_stat, p_val = stats.wilcoxon(mae_morgan, mae_d3d)

    print("\n" + "-" * 70)
    print("Wilcoxon signed-rank test on outer-fold MAE:")
    print(f"  W-statistic = {w_stat:.1f}")
    print(f"  p-value     = {p_val:.4f}")
    print("-" * 70)

    is_sig = "true" if p_val < 0.05 else "false"
    if p_val >= 0.05:
        print("RESULT: No statistically significant difference (p >= 0.05).")
    else:
        print("RESULT: Statistically significant difference (p < 0.05).")

    # Overwrite variables cleanly in latex/wilcoxon_variables.tex
    with open(WILCOXON_LATEX_FILE, 'w', encoding='utf-8') as f:
        f.write("% =====================================================\n")
        f.write("% Auto-generated by 0.1WILCOXON.py\n")
        f.write("% Include in preamble with: \\input{latex/wilcoxon_variables.tex}\n")
        f.write("% =====================================================\n\n")
        f.write(f"\\newcommand{{\\WilcoxonMaeW}}{{{w_stat:.1f}}}\n")
        f.write(f"\\newcommand{{\\WilcoxonMaeP}}{{{p_val:.4f}}}\n")
        f.write(f"\\newcommand{{\\WilcoxonMaeSignificant}}{{{is_sig}}}\n")

    print(f"\n[LATEX] Successfully generated: {WILCOXON_LATEX_FILE}")

if __name__ == "__main__":
    main()
