# =========================================================
# 0.1WILCOXON.py — Paired Wilcoxon & Corrected t-test (Nadeau-Bengio)
# =========================================================
import os
import sys
import pandas as pd
import numpy as np
from scipy import stats

# Link root directory to import paths_config
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from paths_config import CHECKPOINT_FILE, LATEX_DIR

WILCOXON_LATEX_FILE = os.path.join(LATEX_DIR, "wilcoxon_variables.tex")

def main():
    print("=" * 70)
    print("0.1WILCOXON.py — Reading nested_cv_checkpoint.csv directly")
    print("=" * 70)

    if not os.path.exists(CHECKPOINT_FILE):
        print(f"[ERROR] {CHECKPOINT_FILE} not found. Run 0STACK.py first.")
        return

    df = pd.read_csv(CHECKPOINT_FILE)

    # Filter and sort by fold to guarantee exact pairing
    morgan = df[df['Mode'] == 'morgan'].sort_values('Fold')
    d3d = df[df['Mode'] == 'rdkit2d3d_fp'].sort_values('Fold')

    if len(morgan) == 0 or len(d3d) == 0:
        print("[ERROR] Could not find both 'morgan' and 'rdkit2d3d_fp' in checkpoint.")
        return

    mae_morgan = morgan['MAE_outer'].values
    mae_d3d = d3d['MAE_outer'].values

    print(f"Loaded {len(mae_morgan)} folds for 'morgan' and {len(mae_d3d)} folds for 'rdkit2d3d_fp'.")
    print(f"Mean MAE Morgan   : {mae_morgan.mean():.4f} +/- {mae_morgan.std():.4f}")
    print(f"Mean MAE 2D/3D/FP : {mae_d3d.mean():.4f} +/- {mae_d3d.std():.4f}")

    # =========================================================
    # Paired Wilcoxon Signed-Rank Test (Standard)
    # =========================================================
    w_stat, p_val = stats.wilcoxon(mae_morgan, mae_d3d)

    print("\n" + "-" * 70)
    print("Wilcoxon signed-rank test on outer-fold MAE:")
    print(f"  W-statistic = {w_stat:.1f}")
    print(f"  p-value     = {p_val:.4f}")
    print("-" * 70)

    is_sig = "true" if p_val < 0.05 else "false"
    if p_val >= 0.05:
        print("RESULT (Wilcoxon): No statistically significant difference (p >= 0.05).")
    else:
        print("RESULT (Wilcoxon): Statistically significant difference (p < 0.05).")

    # =========================================================
    # Nadeau-Bengio Corrected Paired t-test
    # =========================================================
    n_train_actual = morgan['N_train'].iloc[0]
    n_test_actual = morgan['N_test'].iloc[0]
    n_obs = len(mae_morgan)  # Total folds (e.g., 25 for 5x5)

    diff = mae_morgan - mae_d3d
    mean_diff = diff.mean()
    var_diff = diff.var(ddof=1)

    # Correction factor: 1/K*R + n_test/n_train
    correction = (1.0 / n_obs) + (n_test_actual / n_train_actual)
    se_corrected = np.sqrt(var_diff * correction)

    t_corrected = mean_diff / se_corrected if se_corrected > 0 else 0.0
    df_ttest = n_obs - 1
    p_corrected = 2 * stats.t.sf(np.abs(t_corrected), df=df_ttest) if se_corrected > 0 else 1.0

    print("\n" + "-" * 70)
    print("Nadeau-Bengio Corrected Paired t-test:")
    print(f"  t-statistic = {t_corrected:.3f}")
    print(f"  p-value     = {p_corrected:.4f}")
    print("-" * 70)

    if p_corrected >= 0.05:
        print("RESULT (Nadeau-Bengio): No statistically significant difference (p >= 0.05).")
    else:
        print("RESULT (Nadeau-Bengio): Statistically significant difference (p < 0.05).")

    # =========================================================
    # Export to LaTeX
    # =========================================================
    with open(WILCOXON_LATEX_FILE, 'w', encoding='utf-8') as f:
        f.write("% =====================================================\n")
        f.write("% Auto-generated by 0.1WILCOXON.py\n")
        f.write("% Include in preamble with: \\input{latex/wilcoxon_variables.tex}\n")
        f.write("% =====================================================\n\n")
        f.write(f"\\newcommand{{\\WilcoxonMaeW}}{{{w_stat:.1f}}}\n")
        f.write(f"\\newcommand{{\\WilcoxonMaeP}}{{{p_val:.4f}}}\n")
        f.write(f"\\newcommand{{\\WilcoxonMaeSignificant}}{{{is_sig}}}\n")
        f.write(f"\\newcommand{{\\CorrectedTStat}}{{{t_corrected:.3f}}}\n")
        f.write(f"\\newcommand{{\\CorrectedTP}}{{{p_corrected:.4f}}}\n")

    print(f"\n[LATEX] Successfully generated: {WILCOXON_LATEX_FILE}")

if __name__ == "__main__":
    main()
