import os
import sys
import warnings
from paths_config import *
import numpy as np
import pandas as pd
from rdkit import Chem, RDLogger
from rdkit.Chem import AllChem
from scipy import stats

# =========================================================
# LOGGING SYSTEM SETUP
# =========================================================
class LoggerWriter:
    def __init__(self, filename):
        self.terminal = sys.stdout
        self.log = open(filename, "w", encoding="utf-8")

    def write(self, message):
        self.terminal.write(message)
        self.log.write(message)
        self.log.flush() # Ensure it writes in real-time

    def flush(self):
        self.terminal.flush()
        self.log.flush()

# Create logs directory if it doesn't exist
os.makedirs(LOGS_DIR, exist_ok=True)
log_file_path = os.path.join(LOGS_DIR, "07_molecular_docking.log")

# Redirect stdout to both terminal and log file
sys.stdout = LoggerWriter(log_file_path)

warnings.filterwarnings("ignore")
RDLogger.DisableLog('rdApp.*')

# =========================================================
# CONFIG
# =========================================================
RECEPTOR_FILE  = RECEPTOR_PDBQT
INPUT_CSV      = FDA_CANDIDATES_CSV   # from 2FDA.py
OUTPUT_CSV     = DOCKING_RESULTS_CSV
LATEX_FILE     = LATEX_DOCKING

# Active site coordinates (detected by prep_receptor.py from crystal ligand CP6)
CENTER_X, CENTER_Y, CENTER_Z = 3.689, 39.992, -62.818
BOX_SIZE       = 20.0   # Angstroms
EXHAUSTIVENESS = 32     # Higher = more thorough (8 is standard, 32 is publication quality)
N_POSES        = 3      # Save top 3 poses per ligand

# Thresholds for ML+physics agreement interpretation
ML_ACTIVE_THRESH   = 6.5   # pIC50 > this = predicted active
DOCK_ACTIVE_THRESH = -8.0  # kcal/mol < this = docking confirms binding


# =========================================================
# LIGAND PREPARATION (UPDATED FOR MEEKO v0.5)
# =========================================================
def prepare_ligand_pdbqt(smiles, name):
    """SMILES -> 3D conformer (ETKDGv3 + MMFF94) -> PDBQT string via Meeko."""
    try:
        from meeko import MoleculePreparation
        from meeko import PDBQTWriterLegacy

        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return None

        # Clean salts: Keep only the largest fragment (e.g., removes HCl)
        frags = Chem.GetMolFrags(mol, asMols=True)
        mol = max(frags, key=lambda f: f.GetNumAtoms())

        mol = Chem.AddHs(mol)
        params = AllChem.ETKDGv3()
        params.randomSeed = 42
        if AllChem.EmbedMolecule(mol, params) == -1:
            AllChem.EmbedMolecule(mol, useRandomCoords=True)
        try:
            AllChem.MMFFOptimizeMolecule(mol)
        except Exception:
            pass

        prep = MoleculePreparation()
        mol_setups = prep.prepare(mol)

        # New Meeko syntax to avoid deprecation warnings
        pdbqt_string, is_ok, err = PDBQTWriterLegacy.write_string(mol_setups[0])
        if is_ok:
            return pdbqt_string
        else:
            return None
    except Exception as e:
        return None


# =========================================================
# LATEX EXPORT
# =========================================================
def newcommand(f_handle, name, value):
    f_handle.write(f"\\newcommand{{\\{name}}}{{{value}}}\n")

def export_latex(df_results):
    abs_path = os.path.abspath(LATEX_FILE)
    print(f"\n[LATEX] Attempting to write file to: {abs_path}")

    try:
        os.makedirs(os.path.dirname(abs_path), exist_ok=True)

        with open(abs_path, 'w', encoding='utf-8') as f:
            f.write("% Auto-generated by 3DOCKING.py\n")
            f.write("% Include with: \\input{docking_variables.tex}\n\n")

            n_total    = len(df_results)
            n_validated = len(df_results[
                (df_results['ML_pIC50'] > ML_ACTIVE_THRESH) &
                (df_results['Docking_Score'] < DOCK_ACTIVE_THRESH)
            ])
            n_discordant = len(df_results[
                (df_results['ML_pIC50'] > ML_ACTIVE_THRESH) &
                (df_results['Docking_Score'] >= DOCK_ACTIVE_THRESH)
            ])

            newcommand(f, "DockNTotal",      str(n_total))
            newcommand(f, "DockNValidated",  str(n_validated))
            newcommand(f, "DockNDiscordant", str(n_discordant))
            newcommand(f, "DockExhaustiveness", str(EXHAUSTIVENESS))
            newcommand(f, "DockBoxSize",     str(BOX_SIZE))
            newcommand(f, "DockCenterX",     f"{CENTER_X:.3f}")
            newcommand(f, "DockCenterY",     f"{CENTER_Y:.3f}")
            newcommand(f, "DockCenterZ",     f"{CENTER_Z:.3f}")

            if len(df_results) >= 3:
                rho, p = stats.spearmanr(df_results['ML_pIC50'], df_results['Docking_Score'])
                newcommand(f, "DockSpearmanRho", f"{rho:.3f}")
                newcommand(f, "DockSpearmanP", f"{p:.4f}")

            best = df_results.sort_values('Docking_Score').iloc[0]
            name_safe = "".join(c for c in str(best['Name']) if c.isalpha())[:20]
            newcommand(f, "DockBestCandidate",    name_safe)
            newcommand(f, "DockBestMLpIC",        f"{best['ML_pIC50']:.4f}")
            newcommand(f, "DockBestDockScore",    f"{best['Docking_Score']:.2f}")

            def extract_compound_metrics(file_handle, df, name_substring, prefix):
                match = df[df['Name'].str.contains(name_substring, case=False, na=False)]
                if not match.empty:
                    row = match.iloc[0]
                    newcommand(file_handle, f"{prefix}MLpIC", f"{row['ML_pIC50']:.4f}")
                    newcommand(file_handle, f"{prefix}DockScore", f"{row['Docking_Score']:.2f}")

            extract_compound_metrics(f, df_results, 'Chlorambucil', 'Chlorambucil')
            extract_compound_metrics(f, df_results, 'Bisacodyl', 'Bisacodyl')
            extract_compound_metrics(f, df_results, 'Pyrimethamine', 'Pyrimethamine')
            extract_compound_metrics(f, df_results, 'Folic Acid', 'FolicAcid')
            extract_compound_metrics(f, df_results, 'Methotrexate', 'Methotrexate')
            extract_compound_metrics(f, df_results, 'Triamterene', 'Triamterene')

        print(f"[LATEX] SUCCESS! Variables exported to {abs_path}")

    except Exception as e:
        print(f"[LATEX ERROR] Failed to write .tex file: {e}")


# =========================================================
# MAIN
# =========================================================
def run():
    try:
        from vina import Vina
    except ImportError:
        print("[ERROR] AutoDock Vina Python bindings not installed. "
              "Install with: pip install vina")
        return

    print("=" * 90)
    print("3DOCKING.py — Hybrid ML + Physics Validation (AutoDock Vina)")
    print(f"Receptor: {RECEPTOR_FILE}")
    print(f"Active site center: [{CENTER_X}, {CENTER_Y}, {CENTER_Z}]")
    print(f"Box: {BOX_SIZE}A | Exhaustiveness: {EXHAUSTIVENESS}")
    print(f"Log file: {log_file_path}")
    print("=" * 90)

    if not os.path.exists(RECEPTOR_FILE):
        print(f"[ERROR] {RECEPTOR_FILE} not found. Run prep_receptor.py first.")
        return
    if not os.path.exists(INPUT_CSV):
        print(f"[ERROR] {INPUT_CSV} not found. Run 2FDA.py first.")
        return

    df = pd.read_csv(INPUT_CSV)

    top = df.head(15).copy()
    ref_names = ['Pyrimethamine', 'Trimethoprim', 'Bisacodyl',
                 'Etodolac', 'Triamterene', 'Methotrexate', 'Chlorambucil']
    refs = df[df['Name'].str.contains('|'.join(ref_names), case=False, na=False)]
    candidates = pd.concat([top, refs]).drop_duplicates('CID').reset_index(drop=True)
    print(f"\n[INFO] {len(candidates)} candidates selected for docking")

    v = Vina(sf_name='vina')
    v.set_receptor(RECEPTOR_FILE)
    v.compute_vina_maps(
        center=[CENTER_X, CENTER_Y, CENTER_Z],
        box_size=[BOX_SIZE, BOX_SIZE, BOX_SIZE],
    )

    results = []
    print(f"\n{'Compound':<30} | {'Status':<20} | {'Best pose (kcal/mol)'}")
    print("-" * 70)

    for _, row in candidates.iterrows():
        name   = str(row['Name'])[:28]
        smiles = row['SMILES']
        ml_pic50 = row['pIC50_pred'] if 'pIC50_pred' in row else row.get('CONSENSUS_MEAN', np.nan)

        pdbqt = prepare_ligand_pdbqt(smiles, name)
        if pdbqt is None:
            print(f"{name:<30} | 3D prep failed       |")
            continue

        try:
            v.set_ligand_from_string(pdbqt)

            # REMOVED seed parameter. Vina python API does not support it here.
            v.dock(exhaustiveness=EXHAUSTIVENESS, n_poses=N_POSES)

            energies = v.energies(n_poses=N_POSES)
            best_energy = energies[0][0]
            all_energies = [e[0] for e in energies]

            print(f"{name:<30} | OK                   | {best_energy:.2f}")
            results.append({
                'Name':         row['Name'],
                'CID':          row.get('CID'),
                'SMILES':       smiles,
                'ML_pIC50':     ml_pic50,
                'Docking_Score': best_energy,
                'Docking_Pose2': all_energies[1] if len(all_energies) > 1 else np.nan,
                'Docking_Pose3': all_energies[2] if len(all_energies) > 2 else np.nan,
                'Type':         row.get('Type', ''),
            })
        except Exception as e:
            # Print the actual exception to debug if it fails again
            print(f"{name:<30} | Error: {type(e).__name__} |")

    if not results:
        print("[ERROR] No successful docking results.")
        return

    df_res = pd.DataFrame(results).sort_values('Docking_Score').reset_index(drop=True)

    print("\n" + "=" * 100)
    print("FINAL RESULTS — ML prediction vs. Physics (AutoDock Vina)")
    print("=" * 100)
    print(f"{'Compound':<30} | {'ML pIC50':>9} | {'Vina (kcal/mol)':>15} | {'Agreement'}")
    print("-" * 80)

    for _, r in df_res.iterrows():
        ml   = r['ML_pIC50']
        dock = r['Docking_Score']
        if   ml > ML_ACTIVE_THRESH   and dock < DOCK_ACTIVE_THRESH: status = "VALIDATED (+)"
        elif ml < 6.0                and dock > -7.5:               status = "VALIDATED (-)"
        elif ml > ML_ACTIVE_THRESH   and dock >= DOCK_ACTIVE_THRESH: status = "ML FALSE POSITIVE"
        elif ml < 6.0                and dock < DOCK_ACTIVE_THRESH:  status = "ML FALSE NEGATIVE"
        else:                                                         status = "Neutral"
        print(f"{str(r['Name'])[:28]:<30} | {ml:>9.4f} | {dock:>15.2f} | {status}")

    df_res.to_csv(OUTPUT_CSV, index=False)
    print(f"\n[EXPORT] Results saved to {OUTPUT_CSV}")
    export_latex(df_res)
    print("[DONE] 07_molecular_docking.py complete.")


if __name__ == "__main__":
    run()
