import os
import sys
import time
import warnings
from paths_config import *
import numpy as np
import pandas as pd
from rdkit import Chem, RDLogger
from rdkit.Chem import AllChem, Descriptors, Lipinski
from scipy import stats
from logger_utils import setup_logger

# =========================================================
# LOGGING SYSTEM SETUP
# =========================================================
log_file_path = os.path.join(LOGS_DIR, "07_molecular_docking.log")
setup_logger(log_file_path)

warnings.filterwarnings("ignore")
RDLogger.DisableLog('rdApp.*')


# =========================================================
# LIGAND PREPARATION & PHYSICOPHYSICAL METRICS
# =========================================================
def get_physicochemical_props(smiles):
    """Calcula MW, LogP, Rotatable Bonds y Heavy Atoms usando RDKit."""
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None, None, None, None, None

    frags = Chem.GetMolFrags(mol, asMols=True)
    mol_clean = max(frags, key=lambda f: f.GetNumAtoms())

    mw = Descriptors.MolWt(mol_clean)
    logp = Descriptors.MolLogP(mol_clean)
    rot_bonds = Lipinski.NumRotatableBonds(mol_clean)
    heavy_atoms = mol_clean.GetNumHeavyAtoms()

    return mol_clean, mw, logp, rot_bonds, heavy_atoms

def prepare_ligand_pdbqt(mol_clean):
    """Genera conformación 3D y convierte a PDBQT vía Meeko."""
    try:
        from meeko import MoleculePreparation, PDBQTWriterLegacy

        mol_h = Chem.AddHs(mol_clean)
        params = AllChem.ETKDGv3()
        params.randomSeed = RANDOM_STATE
        if AllChem.EmbedMolecule(mol_h, params) == -1:
            AllChem.EmbedMolecule(mol_h, useRandomCoords=True)
        try:
            AllChem.MMFFOptimizeMolecule(mol_h)
        except Exception:
            pass

        prep = MoleculePreparation()
        mol_setups = prep.prepare(mol_h)
        pdbqt_string, is_ok, _ = PDBQTWriterLegacy.write_string(mol_setups[0])
        return pdbqt_string if is_ok else None
    except Exception as e:
        print(f"    [ligand prep] {type(e).__name__}: {str(e)[:80]}")
        return None


# =========================================================
# LATEX EXPORT
# =========================================================
def newcommand(f_handle, name, value):
    f_handle.write(f"\\newcommand{{\\{name}}}{{{value}}}\n")

def export_latex(df_results):
    abs_path = os.path.abspath(LATEX_DOCKING)
    print(f"\n[LATEX] Attempting to write file to: {abs_path}")

    try:
        os.makedirs(os.path.dirname(abs_path), exist_ok=True)

        with open(abs_path, 'w', encoding='utf-8') as f:
            f.write("% Auto-generated by 07_molecular_docking.py\n")
            f.write("% Include with: \\input{docking_variables.tex}\n\n")

            n_total     = len(df_results)
            n_validated = len(df_results[df_results['Agreement'] == 'VALIDATED (+)'])
            n_discordant = len(df_results[df_results['Agreement'] == 'ML FALSE POSITIVE'])

            newcommand(f, "DockNTotal",      str(n_total))
            newcommand(f, "DockNValidated",  str(n_validated))
            newcommand(f, "DockNDiscordant", str(n_discordant))
            newcommand(f, "DockExhaustiveness", str(EXHAUSTIVENESS))
            newcommand(f, "DockBoxSize",     str(BOX_SIZE))
            newcommand(f, "DockCenterX",     f"{CENTER_X:.3f}")
            newcommand(f, "DockCenterY",     f"{CENTER_Y:.3f}")
            newcommand(f, "DockCenterZ",     f"{CENTER_Z:.3f}")

            if len(df_results) >= 3:
                rho, p = stats.spearmanr(df_results['ML_pIC50'], df_results['Docking_Score'])
                newcommand(f, "DockSpearmanRho", f"{rho:.3f}")
                newcommand(f, "DockSpearmanP", f"{p:.4f}")

            best = df_results.sort_values('Docking_Score').iloc[0]
            name_safe = "".join(c for c in str(best['Name']) if c.isalpha())[:20]
            newcommand(f, "DockBestCandidate",    name_safe)
            newcommand(f, "DockBestMLpIC",        f"{best['ML_pIC50']:.4f}")
            newcommand(f, "DockBestDockScore",    f"{best['Docking_Score']:.2f}")

            def extract_compound_metrics(file_handle, df, name_substring, prefix):
                match = df[df['Name'].str.contains(name_substring, case=False, na=False)]
                if not match.empty:
                    row = match.iloc[0]
                    newcommand(file_handle, f"{prefix}MLpIC", f"{row['ML_pIC50']:.4f}")
                    newcommand(file_handle, f"{prefix}DockScore", f"{row['Docking_Score']:.2f}")

            for search_sub, prefix in LATEX_REF_COMPOUNDS:
                extract_compound_metrics(f, df_results, search_sub, prefix)

        print(f"[LATEX] SUCCESS! Variables exported to {abs_path}")

    except Exception as e:
        print(f"[LATEX ERROR] Failed to write .tex file: {e}")


# =========================================================
# MAIN
# =========================================================
def run():
    try:
        from vina import Vina
    except ImportError:
        print("[ERROR] AutoDock Vina Python bindings not installed.")
        sys.exit(1)

    print("=" * 90)
    print("07_molecular_docking.py — Fully Agnostic Docking Pipeline")
    print(f"Receptor: {RECEPTOR_PDBQT}")
    print(f"Active site center: [{CENTER_X}, {CENTER_Y}, {CENTER_Z}]")
    print(f"Box: {BOX_SIZE}A | Exhaustiveness: {EXHAUSTIVENESS}")
    print(f"Log file: {log_file_path}")
    print("=" * 90)

    if not os.path.exists(RECEPTOR_PDBQT) or not os.path.exists(FDA_CANDIDATES_CSV):
        print("[ERROR] Input files missing (receptor PDBQT or candidates CSV from step 05).")
        sys.exit(1)

    df = pd.read_csv(FDA_CANDIDATES_CSV)
    if 'pIC50_pred' not in df.columns and 'CONSENSUS_MEAN' not in df.columns:
        print("[ERROR] Candidates CSV has neither 'pIC50_pred' nor 'CONSENSUS_MEAN' (ML score column).")
        sys.exit(1)
    top = df.head(TOP_CANDIDATES_COUNT).copy()
    refs = df[df['Name'].str.contains('|'.join(REF_CONTROL_NAMES), case=False, na=False)]

    candidates = pd.concat([top, refs]).drop_duplicates(subset=['SMILES']).reset_index(drop=True)
    print(f"\n[INFO] {len(candidates)} candidates selected for docking")

    v = Vina(sf_name='vina', seed=RANDOM_STATE)   # fixed seed -> reproducible poses/energies
    v.set_receptor(RECEPTOR_PDBQT)
    v.compute_vina_maps(
        center=[CENTER_X, CENTER_Y, CENTER_Z],
        box_size=[BOX_SIZE, BOX_SIZE, BOX_SIZE],
    )

    results = []
    print(f"\n{'Compound':<25} | {'LE':>6} | {'Dock (kcal/mol)':>15} | {'Time (s)':>8}")
    print("-" * 65)

    for _, row in candidates.iterrows():
        name     = str(row['Name'])[:24]
        smiles   = row['SMILES']
        ml_pic50 = row['pIC50_pred'] if 'pIC50_pred' in row else row.get('CONSENSUS_MEAN', np.nan)

        t_start_prep = time.time()
        mol_clean, mw, logp, rot_bonds, heavy_atoms = get_physicochemical_props(smiles)

        if mol_clean is None:
            print(f"{name:<25} | Invalid SMILES")
            continue

        pdbqt = prepare_ligand_pdbqt(mol_clean)
        t_prep = time.time() - t_start_prep

        if pdbqt is None:
            print(f"{name:<25} | 3D prep failed")
            continue

        try:
            t_start_dock = time.time()
            v.set_ligand_from_string(pdbqt)
            v.dock(exhaustiveness=EXHAUSTIVENESS, n_poses=N_POSES)
            t_dock = time.time() - t_start_dock

            energies = v.energies(n_poses=N_POSES)
            best_energy = energies[0][0]
            all_energies = [e[0] for e in energies]

            le = best_energy / heavy_atoms if heavy_atoms and heavy_atoms > 0 else np.nan
            energy_gap = energies[-1][0] - best_energy if len(energies) > 1 else 0.0
            max_rmsd_ub = max([e[2] for e in energies]) if len(energies) > 1 else 0.0

            if ml_pic50 > ML_ACTIVE_THRESH and best_energy < DOCK_ACTIVE_THRESH:
                agreement = "VALIDATED (+)"
            elif ml_pic50 < 6.0 and best_energy > -7.5:
                agreement = "VALIDATED (-)"
            elif ml_pic50 > ML_ACTIVE_THRESH and best_energy >= DOCK_ACTIVE_THRESH:
                agreement = "ML FALSE POSITIVE"
            elif ml_pic50 < 6.0 and best_energy < DOCK_ACTIVE_THRESH:
                agreement = "ML FALSE NEGATIVE"
            else:
                agreement = "Neutral"

            print(f"{name:<25} | {le:>6.3f} | {best_energy:>15.2f} | {t_prep + t_dock:>8.2f}s")

            results.append({
                'Name':              row['Name'],
                'CID':               row.get('CID'),
                'SMILES':            smiles,
                'ML_pIC50':          round(ml_pic50, 4),
                'Docking_Score':     round(best_energy, 2),
                'Ligand_Efficiency': round(le, 4) if not np.isnan(le) else np.nan,
                'Energy_Gap_P1_Pn':  round(energy_gap, 3),
                'Max_RMSD_UB':       round(max_rmsd_ub, 3),
                'MW':                round(mw, 2) if mw else np.nan,
                'LogP':              round(logp, 2) if logp else np.nan,
                'Rotatable_Bonds':   rot_bonds,
                'Heavy_Atoms':       heavy_atoms,
                'T_prep_sec':        round(t_prep, 3),
                'T_dock_sec':        round(t_dock, 3),
                'T_total_sec':       round(t_prep + t_dock, 3),
                'Agreement':         agreement,
                'Docking_Pose2':     round(all_energies[1], 2) if len(all_energies) > 1 else np.nan,
                'Docking_Pose3':     round(all_energies[2], 2) if len(all_energies) > 2 else np.nan,
                'Type':              row.get('Type', ''),
            })

        except Exception as e:
            print(f"{name:<25} | Error: {type(e).__name__} - {str(e)[:30]}")

    if not results:
        print("[ERROR] No successful docking results.")
        sys.exit(1)

    df_res = pd.DataFrame(results).sort_values('Docking_Score').reset_index(drop=True)

    print("\n" + "=" * 100)
    print("FINAL RESULTS ENRICHED — ML Prediction vs. Physics (AutoDock Vina)")
    print("=" * 100)
    print(f"{'Compound':<25} | {'ML pIC50':>9} | {'Vina':>8} | {'LE':>7} | {'Agreement'}")
    print("-" * 80)

    for _, r in df_res.iterrows():
        print(f"{str(r['Name'])[:24]:<25} | {r['ML_pIC50']:>9.4f} | {r['Docking_Score']:>8.2f} | {r['Ligand_Efficiency']:>7.3f} | {r['Agreement']}")

    df_res.to_csv(DOCKING_RESULTS_CSV, index=False)
    print(f"\n[EXPORT] Enriched dataset saved to {DOCKING_RESULTS_CSV}")
    export_latex(df_res)
    print("[DONE] 07_molecular_docking.py complete.")


if __name__ == "__main__":
    run()