import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from adjustText import adjust_text
from paths_config import FDA_ADMET_CANDIDATES_CSV, FIGURES_DIR

def plot_admet_quadrants():
    # Construct path to full pre-filter dataset generated by 08_admet_profiling.py
    input_csv = FDA_ADMET_CANDIDATES_CSV.replace(".csv", "_FULL_PRE_FILTER.csv")

    print(f"[-] Reading full ADMET dataset from: {input_csv}")
    if not os.path.exists(input_csv):
        print(f"[ERROR] CSV file not found: {input_csv}")
        return

    df = pd.read_csv(input_csv)

    fig, ax = plt.subplots(figsize=(10, 6.5))
    sns.set_theme(style="whitegrid", context="paper")

    # Semantic color mapping for ADMET profiles
    custom_palette = {
        'ADMET-Compliant (Oral)': '#2ca02c',                # Green
        'Parenteral Candidate (Low Caco-2)': '#1f77b4',     # Blue
        'Flagged: High hERG Cardiotoxicity Risk': '#d62728' # Red
    }

    # Define threshold boundaries based on screening thresholds
    herg_threshold = 0.5
    caco2_passing = df[df['Caco2_Pass'] == True]['Caco2_Permeability']
    caco2_threshold = caco2_passing.min() if not caco2_passing.empty else -5.15

    # Configure axes limits with padding
    y_max = df['Caco2_Permeability'].max() + 0.2
    y_min = df['Caco2_Permeability'].min() - 0.2
    x_min = df['hERG_Blocker_Prob'].min() - 0.05
    x_max = df['hERG_Blocker_Prob'].max() + 0.05

    ax.set_ylim(y_min, y_max)
    ax.set_xlim(x_min, x_max)

    # Shade the optimal ADMET quadrant (Low hERG toxicity, High Caco-2 permeability)
    ax.fill_between([x_min, herg_threshold], caco2_threshold, y_max,
                    color='#2ca02c', alpha=0.06, zorder=0, label='Optimal Profile Zone')

    # Main scatter plot layer
    sns.scatterplot(
        data=df,
        x='hERG_Blocker_Prob',
        y='Caco2_Permeability',
        hue='ADMET_Profile',
        palette=custom_palette,
        s=120,
        alpha=0.85,
        edgecolor='white',
        linewidth=1.0,
        ax=ax,
        zorder=3
    )

    # Risk and permeability threshold guidelines
    ax.axvline(x=herg_threshold, color='#555555', linestyle='--', alpha=0.6, linewidth=1.2, zorder=1)
    ax.axhline(y=caco2_threshold, color='#555555', linestyle=':', alpha=0.6, linewidth=1.2, zorder=1)

    # Filter and instantiate annotation text elements
    texts = []
    seen_names = set()
    seen_coords = set()

    for _, row in df.iterrows():
        full_name = str(row['Name']).strip()
        first_word = full_name.lower().split()[0]

        # Deduplicate compounds by root name and coordinates
        if first_word in seen_names:
            continue

        coord_key = (round(row['hERG_Blocker_Prob'], 3), round(row['Caco2_Permeability'], 2))
        if coord_key in seen_coords:
            continue

        seen_names.add(first_word)
        seen_coords.add(coord_key)

        # Add text element with minor coordinate offset to clear marker centers
        texts.append(ax.text(
            row['hERG_Blocker_Prob'] + 0.01,
            row['Caco2_Permeability'] + 0.01,
            full_name,
            ha='left',
            va='bottom',
            fontsize=7,
            alpha=0.9,
            zorder=10
        ))

    # Resolve text overlaps against dataset coordinates
    adjust_text(
        texts,
        x=df['hERG_Blocker_Prob'].tolist(),
        y=df['Caco2_Permeability'].tolist(),
        force_points=(2.5, 2.5),
        force_text=(1.5, 1.5),
        expand_points=(2.0, 2.0),
        arrowprops=dict(
            arrowstyle="-",
            color='#999999',
            lw=0.6,
            alpha=0.7,
            shrinkA=0,  # Prevents FancyArrowPatch transform warning
            shrinkB=3   # Buffer gap before marker edge
        )
    )

    # Quadrant indicator text boxes
    bbox_props = dict(boxstyle="round,pad=0.3", fc="white", ec="none", alpha=0.8)
    ax.text(x_min + 0.02, y_max - 0.05, 'SAFE & ORAL\n(Ideal Candidates)',
            color='#2ca02c', fontsize=8, fontweight='bold', bbox=bbox_props, ha='left', va='top')
    ax.text(x_max - 0.02, y_max - 0.05, 'TOXIC RISK\n(hERG Blockers)',
            color='#d62728', fontsize=8, fontweight='bold', bbox=bbox_props, ha='right', va='top')

    # Axis titles and labels
    ax.set_title('ADMET Profiling: hERG Toxicity vs Caco-2 Permeability', pad=15, fontsize=12, fontweight='bold')
    ax.set_xlabel('hERG Blocker Probability (Risk of Cardiotoxicity) → [Lower is Better]', fontsize=10, fontweight='medium')
    ax.set_ylabel('Caco-2 Permeability → [Higher is Better]', fontsize=10, fontweight='medium')

    # External legend layout configuration
    ax.legend(
        bbox_to_anchor=(1.04, 1),
        loc='upper left',
        borderaxespad=0.,
        fontsize=8.5,
        title_fontsize=9.5,
        markerscale=0.8,
        frameon=True,
        edgecolor='lightgray'
    )

    plt.tight_layout()

    os.makedirs(FIGURES_DIR, exist_ok=True)
    out_path = os.path.join(FIGURES_DIR, '08_admet_quadrants.png')
    plt.savefig(out_path, dpi=300, bbox_inches='tight')
    print(f"[+] ADMET figure saved successfully at: {out_path}")
    plt.close()

if __name__ == "__main__":
    plot_admet_quadrants()
