import os
import warnings
from paths_config import *
import numpy as np
import pandas as pd
from rdkit import Chem, RDLogger
from rdkit.Chem import AllChem
from scipy import stats

warnings.filterwarnings("ignore")
RDLogger.DisableLog('rdApp.*')

# =========================================================
# CONFIG
# =========================================================
RECEPTOR_FILE  = RECEPTOR_PDBQT
INPUT_CSV      = FDA_CANDIDATES_CSV   # from 2FDA.py
OUTPUT_CSV     = DOCKING_RESULTS_CSV
LATEX_FILE     = LATEX_DOCKING

# Active site coordinates (detected by prep_receptor.py from crystal ligand CP6)
CENTER_X, CENTER_Y, CENTER_Z = 3.689, 39.992, -62.818
BOX_SIZE       = 20.0   # Angstroms
EXHAUSTIVENESS = 32     # Higher = more thorough (8 is standard, 32 is publication quality)
N_POSES        = 3      # Save top 3 poses per ligand

# Thresholds for ML+physics agreement interpretation
ML_ACTIVE_THRESH   = 6.5   # pIC50 > this = predicted active
DOCK_ACTIVE_THRESH = -8.0  # kcal/mol < this = docking confirms binding


# =========================================================
# LIGAND PREPARATION
# =========================================================
def prepare_ligand_pdbqt(smiles, name):
    """SMILES -> 3D conformer (ETKDGv3 + MMFF94) -> PDBQT string via Meeko."""
    try:
        from meeko import MoleculePreparation
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return None
        mol = Chem.AddHs(mol)
        params = AllChem.ETKDGv3()
        params.randomSeed = 42
        if AllChem.EmbedMolecule(mol, params) == -1:
            AllChem.EmbedMolecule(mol, useRandomCoords=True)
        try:
            AllChem.MMFFOptimizeMolecule(mol)
        except Exception:
            pass
        prep = MoleculePreparation()
        prep.prepare(mol)
        return prep.write_pdbqt_string()
    except Exception:
        return None


# =========================================================
# LATEX EXPORT
# =========================================================
# =========================================================
# LATEX EXPORT
# =========================================================
def newcommand(f, name, value):
    f.write(f"\\newcommand{{\\{name}}}{{{value}}}\n")

def export_latex(df_results):
    with open(LATEX_FILE, 'w', encoding='utf-8') as f:
        f.write("% Auto-generated by 3DOCKING.py\n")
        f.write("% Include with: \\input{docking_variables.tex}\n\n")

        n_total    = len(df_results)
        n_validated = len(df_results[
            (df_results['ML_pIC50'] > ML_ACTIVE_THRESH) &
            (df_results['Docking_Score'] < DOCK_ACTIVE_THRESH)
        ])
        n_discordant = len(df_results[
            (df_results['ML_pIC50'] > ML_ACTIVE_THRESH) &
            (df_results['Docking_Score'] >= DOCK_ACTIVE_THRESH)
        ])

        newcommand(f, "DockNTotal",      str(n_total))
        newcommand(f, "DockNValidated",  str(n_validated))
        newcommand(f, "DockNDiscordant", str(n_discordant))
        newcommand(f, "DockExhaustiveness", str(EXHAUSTIVENESS))
        newcommand(f, "DockBoxSize",     str(BOX_SIZE))
        newcommand(f, "DockCenterX",     f"{CENTER_X:.3f}")
        newcommand(f, "DockCenterY",     f"{CENTER_Y:.3f}")
        newcommand(f, "DockCenterZ",     f"{CENTER_Z:.3f}")

        # Pearson correlation ML pIC50 vs Docking score
        if len(df_results) >= 3:
            r, p = stats.pearsonr(df_results['ML_pIC50'], df_results['Docking_Score'])
            newcommand(f, "DockPearsonR", f"{r:.3f}")
            newcommand(f, "DockPearsonP", f"{p:.4f}")

        # Best candidate
        best = df_results.sort_values('Docking_Score').iloc[0]
        name_safe = "".join(c for c in str(best['Name']) if c.isalpha())[:20]
        newcommand(f, "DockBestCandidate",    name_safe)
        newcommand(f, "DockBestMLpIC",        f"{best['ML_pIC50']:.4f}") # Fixed macro name to match LaTeX
        newcommand(f, "DockBestDockScore",    f"{best['Docking_Score']:.2f}")

        # Dynamic extraction for true negative example (Chlorambucil)
        chlorambucil = df_results[df_results['Name'].str.contains('Chlorambucil', case=False, na=False)]
        if not chlorambucil.empty:
            c_row = chlorambucil.iloc[0]
            newcommand(f, "ChlorambucilMLpIC", f"{c_row['ML_pIC50']:.2f}")
            newcommand(f, "ChlorambucilDockScore", f"{c_row['Docking_Score']:.2f}")

    print(f"[LATEX] Docking variables exported to {LATEX_FILE}")

# =========================================================
# MAIN
# =========================================================
def run():
    try:
        from vina import Vina
    except ImportError:
        print("[ERROR] AutoDock Vina Python bindings not installed. "
              "Install with: pip install vina")
        return

    print("=" * 90)
    print("3DOCKING.py — Hybrid ML + Physics Validation (AutoDock Vina)")
    print(f"Receptor: {RECEPTOR_FILE}")
    print(f"Active site center: [{CENTER_X}, {CENTER_Y}, {CENTER_Z}]")
    print(f"Box: {BOX_SIZE}A | Exhaustiveness: {EXHAUSTIVENESS}")
    print("=" * 90)

    if not os.path.exists(RECEPTOR_FILE):
        print(f"[ERROR] {RECEPTOR_FILE} not found. Run prep_receptor.py first.")
        return
    if not os.path.exists(INPUT_CSV):
        print(f"[ERROR] {INPUT_CSV} not found. Run 2FDA.py first.")
        return

    df = pd.read_csv(INPUT_CSV)

    # Select candidates: top 15 by pIC50 + paper reference drugs + Chlorambucil
    top = df.head(15).copy()
    ref_names = ['Pyrimethamine', 'Trimethoprim', 'Bisacodyl',
                 'Etodolac', 'Triamterene', 'Methotrexate', 'Chlorambucil']
    refs = df[df['Name'].str.contains('|'.join(ref_names), case=False, na=False)]
    candidates = pd.concat([top, refs]).drop_duplicates('CID').reset_index(drop=True)
    print(f"\n[INFO] {len(candidates)} candidates selected for docking")

    # Configure Vina
    v = Vina(sf_name='vina')
    v.set_receptor(RECEPTOR_FILE)
    v.compute_vina_maps(
        center=[CENTER_X, CENTER_Y, CENTER_Z],
        box_size=[BOX_SIZE, BOX_SIZE, BOX_SIZE],
    )

    results = []
    print(f"\n{'Compound':<30} | {'Status':<20} | {'Best pose (kcal/mol)'}")
    print("-" * 70)

    for _, row in candidates.iterrows():
        name   = str(row['Name'])[:28]
        smiles = row['SMILES']
        ml_pic50 = row['pIC50_pred'] if 'pIC50_pred' in row else row.get('CONSENSUS_MEAN', np.nan)

        pdbqt = prepare_ligand_pdbqt(smiles, name)
        if pdbqt is None:
            print(f"{name:<30} | 3D prep failed       |")
            continue

        try:
            v.set_ligand_from_string(pdbqt)
            v.dock(exhaustiveness=EXHAUSTIVENESS, n_poses=N_POSES)
            energies = v.energies(n_poses=N_POSES)
            best_energy = energies[0][0]
            all_energies = [e[0] for e in energies]

            print(f"{name:<30} | OK                   | {best_energy:.2f}")
            results.append({
                'Name':         row['Name'],
                'CID':          row.get('CID'),
                'SMILES':       smiles,
                'ML_pIC50':     ml_pic50,
                'Docking_Score': best_energy,
                'Docking_Pose2': all_energies[1] if len(all_energies) > 1 else np.nan,
                'Docking_Pose3': all_energies[2] if len(all_energies) > 2 else np.nan,
                'Type':         row.get('Type', ''),
            })
        except Exception:
            print(f"{name:<30} | Vina error            |")

    if not results:
        print("[ERROR] No successful docking results.")
        return

    df_res = pd.DataFrame(results).sort_values('Docking_Score').reset_index(drop=True)

    # ── Results table ─────────────────────────────────────────────────────────
    print("\n" + "=" * 100)
    print("FINAL RESULTS — ML prediction vs. Physics (AutoDock Vina)")
    print("=" * 100)
    print(f"{'Compound':<30} | {'ML pIC50':>9} | {'Vina (kcal/mol)':>15} | {'Agreement'}")
    print("-" * 80)

    for _, r in df_res.iterrows():
        ml   = r['ML_pIC50']
        dock = r['Docking_Score']
        if   ml > ML_ACTIVE_THRESH   and dock < DOCK_ACTIVE_THRESH: status = "VALIDATED (+)"
        elif ml < 6.0                and dock > -7.5:               status = "VALIDATED (-)"
        elif ml > ML_ACTIVE_THRESH   and dock >= DOCK_ACTIVE_THRESH: status = "ML FALSE POSITIVE"
        elif ml < 6.0                and dock < DOCK_ACTIVE_THRESH:  status = "ML FALSE NEGATIVE"
        else:                                                         status = "Neutral"
        print(f"{str(r['Name'])[:28]:<30} | {ml:>9.4f} | {dock:>15.2f} | {status}")

    # ── Correlation ───────────────────────────────────────────────────────────
    if len(df_res) >= 3:
        r_val, p_val = stats.pearsonr(df_res['ML_pIC50'], df_res['Docking_Score'])
        print(f"\nPearson correlation (ML pIC50 vs Docking Score): r={r_val:.3f}, p={p_val:.4f}")
        print("(Negative r expected: higher pIC50 should correlate with more negative docking energy)")

    # ── Executive summary ─────────────────────────────────────────────────────
    n_validated  = len(df_res[(df_res['ML_pIC50'] > ML_ACTIVE_THRESH) &
                               (df_res['Docking_Score'] < DOCK_ACTIVE_THRESH)])
    n_discordant = len(df_res[(df_res['ML_pIC50'] > ML_ACTIVE_THRESH) &
                               (df_res['Docking_Score'] >= DOCK_ACTIVE_THRESH)])
    best = df_res.iloc[0]

    print("\n" + "=" * 100)
    print("EXECUTIVE SUMMARY — paste into Results/Discussion")
    print("=" * 100)
    print(f"- {n_validated}/{len(df_res)} compounds show ML-physics agreement "
          f"(pIC50>{ML_ACTIVE_THRESH} AND docking<{DOCK_ACTIVE_THRESH} kcal/mol)")
    print(f"- {n_discordant} compounds flagged as potential ML false positives "
          f"(high pIC50 but weak docking score)")
    print(f"- Best docking candidate: {best['Name']} "
          f"(ML pIC50={best['ML_pIC50']:.4f}, Vina={best['Docking_Score']:.2f} kcal/mol)")
    if len(df_res) >= 3:
        print(f"- Pearson r(ML, docking)={r_val:.3f} (p={p_val:.4f}) — "
              f"{'significant' if p_val < 0.05 else 'not significant'} correlation")

    df_res.to_csv(OUTPUT_CSV, index=False)
    print(f"\n[EXPORT] Results saved to {OUTPUT_CSV}")
    export_latex(df_res)
    print("[DONE] 3DOCKING.py complete.")


if __name__ == "__main__":
    run()
